let name = "Дмитро";
let isStudent = true; 
let myString = "Життя не шахмати, одного мата не вистачить"; 
let myNumber = 42; 
myNumber += 10;
let myNull = null;
let userName = prompt("Luka Herzig");
alert("Привіт, " + userName + "!");
console.log(myNull);
console.log(myNumber);
console.log(myString);
console.log(isStudent);
console.log(name);